version: '3'

vars:
  TARGET: target
  THEME: rocketspacer

tasks:
  clean:
    desc: 'Removes the temporary directory'
    cmds:
      - rm -rf target node_modules
  setup:
    desc: 'Creates the target directory for artifacts and temporary files'
    cmds:
      - mkdir -p {{.TARGET}}
    status:
      - test -d {{.TARGET}}
  install:
    desc: 'Installs the project dependencies'
    deps:
      - setup
    cmds:
      - yarn install
  validate:
    desc: 'Runs schema validation'
    cmds:
      - yarn exec -- resume validate --resume src/resume.json validate
    # TODO: Remove once jsonresume schema supports certifications
    ignore_error: true
    deps:
      - install
  build:
    desc: 'Creates resume index.html under target directory'
    deps:
      - validate
    cmds:
      - rm -f {{.TARGET}}/index.html
      - yarn exec -- resume export --resume src/resume.json --theme {{.THEME}} {{.TARGET}}/index.html
  serve:
    desc: 'Serves the resume on localhost'
    deps:
      - validate
    cmds:
      - yarn exec -- resume serve --resume src/resume.json --silent --dir {{.TARGET}} --theme {{.THEME}}
  pdf:
    desc: 'Generate a pdf file'
    deps:
      - validate
    cmds:
      - yarn exec -- resume export --resume src/resume.json --theme {{.THEME}} --format pdf {{.TARGET}}/resume.pdf
