version: '2'

vars:
  TARGET: target
  THEME: rocketspacer

tasks:
  clean:
    desc: 'Removes the temporary directory'
    cmds:
      - rm -rf target node_modules
  setup:
    desc: 'Creates the target directory for artifacts and temporary files'
    cmds:
      - mkdir -p {{.TARGET}}
    status:
      - test -d {{.TARGET}}
  install:
    desc: 'Installs the project dependencies'
    deps:
      - setup
    cmds:
      - yarn install --ignore-engines
  validate:
    desc: 'Runs schema validation'
    # TODO: resume cli only supports --resume option for server
    # remove dir:src once the CLI supports --resume option for all sub-commands
    dir: src
    cmds:
      - yarn exec -- resume test
    # TODO: Remove once jsonresume schema supports certifications
    ignore_error: true
    deps:
      - install
  build:
    desc: 'Creates resume index.html under target directory'
    deps:
      - validate
    # TODO: resume cli only supports --resume option for server
    # remove dir:src once the CLI supports --resume option for all sub-commands
    dir: src
    cmds:
      - rm -f ../{{.TARGET}}/index.html
      - yarn exec -- resume export --theme {{.THEME}} ../{{.TARGET}}/index.html
  serve:
    desc: 'Serves the resume on localhost'
    deps:
      - validate
    cmds:
      - yarn exec -- resume serve --resume src/resume.json --silent --dir {{.TARGET}} --theme {{.THEME}}
