name: "Build and Publish Resume"
on:
  push:
    branches:
      - main

jobs:
  publish_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Setup NodeJS
        uses: actions/setup-node@v2.3.2
      - name: Setup TaskFile
        uses: arduino/actions/setup-taskfile@master
      - name: Build
        run: task build

